# Generated by Django 3.2.9 on 2022-12-02 22:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='material_color',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
